### ISSUE TITLE
Option to generate "plain" wasm

### ISSUE THREAD

**Issue by GordonSmith** [bytecodealliance/componentize-js#25]
Not sure if this issue should target JCO - but I would like access to the "hello.wasm" as well as the "hello.component.wasm".

Side question - I was expecting to be able to extract the "hello.wasm" from "hello.component.wasm" directly, but didn't find anyway with wasm-tools or wit-bindgen - ended up having to call jco transpile...

**Comment by guybedford** [comment]
This is possible with wasm-tools metadata to determine the binary offsets.

The usage is:

```
import { metadataShow } from '@bytecodealliance/jco';

const coreModules = metadataShow(componentBytes).slice(1, -1).map(({ range: [start, end] }) => componentBytes.slice(start, end));
```

**Comment by GordonSmith** [comment]
FWIW this is what I ended up using:
```
metadataShow(component).slice(1, -1).forEach(({ range: [start, end] }, i) => {
    writeFile(`hello.core${i === 0 ? "" : i}.wasm`, component.slice(start, end));
    return component.slice(start, end);
});
```
