### ISSUE TITLE
Componentize-js: support resources in JS bindgen

### ISSUE THREAD

**Issue by pchickey** [bytecodealliance/componentize-js#62]

**Comment by guybedford** [comment]
Previous draft in https://github.com/bytecodealliance/componentize-js/tree/resources.

**Comment by dicej** [comment]
I'm currently working on this, picking up where @guybedford left off.  The two existing resources tests now pass, although there's still more work to do and tests to add.

https://github.com/dicej/componentize-js/tree/resources
https://github.com/dicej/jco/tree/resources

See also https://github.com/bytecodealliance/componentize-js/issues/57

**Comment by dicej** [comment]
I've opened draft PRs for this:
https://github.com/bytecodealliance/jco/pull/215
https://github.com/bytecodealliance/componentize-js/pull/65

The work is basically done, modulo some refactoring @guybedford is doing on the host binding generator to fix a name clash bug that breaks the `resource-floats` test.  Once that's been merged, I'll move the PRs out of draft.

**Comment by guybedford** [comment]
Landed in https://github.com/bytecodealliance/componentize-js/pull/65.
